import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "pt" | "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Header
    "welcome": "bem-vindo",
    "home": "início",
    "profile": "perfil",
    "marketplace": "marketplace",
    "logout": "sair",
    "login": "entrar",
    "register": "cadastrar",
    "search": "Buscar...",
    // Index
    "index.description": "Conectados em Sergipe é uma rede social que conecta pessoas através de comunidades em Sergipe.",
    "index.cta": "para começar.",
    "index.register": "Cadastre-se",
    "index.or": "ou",
    "index.login": "Entre",
    "guest_user": "Visitante",
    "login_to_see": "Entre para ver seu perfil",
    // PostFeed
    "the_wall": "O Mural",
    "write_something": "Escreva algo:",
    "whats_on_mind": "O que está na sua mente?",
    "post": "Postar",
    // FriendsSidebar
    "friends": "Amigos",
    "see_all_friends": "Ver Todos os Amigos",
    "photo": "foto",
    // Profile
    "profile_of": "Perfil de",
    "change_photo": "Alterar foto",
    "click_to_change": "Clique para alterar a foto",
    "name": "Nome",
    "email": "Email",
    "school": "Escola",
    "member_since": "Membro desde",
    "bio": "Bio",
    "no_bio": "Sem bio ainda.",
    "edit_profile": "Editar Perfil",
    "save": "Salvar",
    "cancel": "Cancelar",
    // Login
    "login.email": "Email:",
    "login.password": "Senha:",
    "login.demo": "Demo:",
    "login.invalid": "Email ou senha inválidos.",
    "login.welcome_title": "[ Bem-vindo ao Conectados em Sergipe ]",
    "login.welcome_text": "Conectados em Sergipe é uma rede social que conecta pessoas através de comunidades em Sergipe.",
    "login.opened": "Abrimos o Conectados em Sergipe para todos em",
    "login.use_for": "Você pode usar o Conectados em Sergipe para:",
    "login.feature1": "Buscar pessoas na sua escola",
    "login.feature2": "Descobrir quem está nas suas turmas",
    "login.feature3": "Encontrar amigos dos seus amigos",
    "login.feature4": "Ver uma visualização da sua rede social",
    "login.get_started": "Para começar, clique abaixo para se cadastrar. Se já tem conta, faça login.",
    "login.about": "sobre",
    "login.welcome_bar": "Bem-vindo ao Conectados em Sergipe!",
    // Register
    "register.title": "Cadastro no [ Conectados em Sergipe ]",
    "register.description": "Conectados em Sergipe é uma rede social para pessoas de Sergipe.",
    "register.full_name": "Nome Completo:",
    "register.email": "Email:",
    "register.password": "Senha:",
    "register.school": "Escola:",
    "register.school_placeholder": "Universidade de São Paulo",
    "register.submit": "Cadastrar",
    "register.already": "Já tem uma conta?",
    "register.login_here": "Entre aqui",
    "register.email_exists": "Já existe uma conta com este email.",
    // Search
    "search.results_for": "Resultados da busca por",
    "search.people": "Pessoas",
    "search.shops": "Lojas",
    "search.no_results": "Nenhum resultado encontrado para",
    // Marketplace
    "marketplace.title": "Marketplace",
    "marketplace.sell": "+ Vender Item",
    "marketplace.cancel": "Cancelar",
    "marketplace.item_title": "Título:",
    "marketplace.price": "Preço:",
    "marketplace.category": "Categoria:",
    "marketplace.description": "Descrição:",
    "marketplace.post_item": "Publicar Item",
    "marketplace.seller": "Vendedor",
    "marketplace.no_items": "Nenhum item nesta categoria.",
    "marketplace.all": "Todos",
    "marketplace.books": "Livros",
    "marketplace.electronics": "Eletrônicos",
    "marketplace.clothing": "Roupas",
    "marketplace.other": "Outros",
    // Footer
    "footer.production": "uma produção Jairo dos Santos",
    "footer.about": "sobre",
    "footer.contact": "contato",
    "footer.privacy": "privacidade",
    "footer.terms": "termos",
    // ProfileSidebar
    "sidebar.info": "Info",
    "sidebar.member_since": "Membro desde: Fevereiro 2004",
    "sidebar.status": "Status: Estudante",
    "sidebar.looking_for": "Buscando: Amizade",
    // Friends
    "friends.requests": "Pedidos de Amizade",
    "friends.accept": "Aceitar",
    "friends.reject": "Recusar",
    "friends.add": "Adicionar",
    "friends.already": "Amigos",
    "friends.pending": "Pendente",
    "friends.none": "Nenhum amigo ainda.",
  },
  es: {
    "welcome": "bienvenido",
    "home": "inicio",
    "profile": "perfil",
    "marketplace": "marketplace",
    "logout": "salir",
    "login": "entrar",
    "register": "registrarse",
    "search": "Buscar...",
    "index.description": "Conectados en Sergipe es una red social que conecta personas a través de comunidades en Sergipe.",
    "index.cta": "para empezar.",
    "index.register": "Regístrate",
    "index.or": "o",
    "index.login": "Inicia sesión",
    "guest_user": "Visitante",
    "login_to_see": "Inicia sesión para ver tu perfil",
    "the_wall": "El Muro",
    "write_something": "Escribe algo:",
    "whats_on_mind": "¿Qué tienes en mente?",
    "post": "Publicar",
    "friends": "Amigos",
    "see_all_friends": "Ver Todos los Amigos",
    "photo": "foto",
    "profile_of": "Perfil de",
    "change_photo": "Cambiar foto",
    "click_to_change": "Haz clic para cambiar la foto",
    "name": "Nombre",
    "email": "Correo",
    "school": "Universidad",
    "member_since": "Miembro desde",
    "bio": "Bio",
    "no_bio": "Sin bio todavía.",
    "edit_profile": "Editar Perfil",
    "save": "Guardar",
    "cancel": "Cancelar",
    "login.email": "Correo:",
    "login.password": "Contraseña:",
    "login.demo": "Demo:",
    "login.invalid": "Correo o contraseña inválidos.",
    "login.welcome_title": "[ Bienvenido a Conectados en Sergipe ]",
    "login.welcome_text": "Conectados en Sergipe es una red social que conecta personas a través de comunidades en Sergipe.",
    "login.opened": "Hemos abierto Conectados en Sergipe para todos en",
    "login.use_for": "Puedes usar Conectados en Sergipe para:",
    "login.feature1": "Buscar personas en tu universidad",
    "login.feature2": "Descubrir quién está en tus clases",
    "login.feature3": "Encontrar amigos de tus amigos",
    "login.feature4": "Ver una visualización de tu red social",
    "login.get_started": "Para empezar, haz clic abajo para registrarte. Si ya tienes cuenta, inicia sesión.",
    "login.about": "acerca de",
    "login.welcome_bar": "¡Bienvenido a Conectados en Sergipe!",
    "register.title": "Registro en [ Conectados en Sergipe ]",
    "register.description": "Conectados en Sergipe es una red social para personas de Sergipe.",
    "register.full_name": "Nombre Completo:",
    "register.email": "Correo:",
    "register.password": "Contraseña:",
    "register.school": "Universidad:",
    "register.school_placeholder": "Universidad de Buenos Aires",
    "register.submit": "Registrarse",
    "register.already": "¿Ya tienes una cuenta?",
    "register.login_here": "Inicia sesión aquí",
    "register.email_exists": "Ya existe una cuenta con este correo.",
    "search.results_for": "Resultados de búsqueda para",
    "search.people": "Personas",
    "search.shops": "Tiendas",
    "search.no_results": "No se encontraron resultados para",
    "marketplace.title": "Marketplace",
    "marketplace.sell": "+ Vender Artículo",
    "marketplace.cancel": "Cancelar",
    "marketplace.item_title": "Título:",
    "marketplace.price": "Precio:",
    "marketplace.category": "Categoría:",
    "marketplace.description": "Descripción:",
    "marketplace.post_item": "Publicar Artículo",
    "marketplace.seller": "Vendedor",
    "marketplace.no_items": "No hay artículos en esta categoría.",
    "marketplace.all": "Todos",
    "marketplace.books": "Libros",
    "marketplace.electronics": "Electrónicos",
    "marketplace.clothing": "Ropa",
    "marketplace.other": "Otros",
    "footer.production": "una producción de Jairo dos Santos",
    "footer.about": "acerca de",
    "footer.contact": "contacto",
    "footer.privacy": "privacidad",
    "footer.terms": "términos",
    "sidebar.info": "Info",
    "sidebar.member_since": "Miembro desde: Febrero 2004",
    "sidebar.status": "Estado: Estudiante",
    "sidebar.looking_for": "Buscando: Amistad",
    "friends.requests": "Solicitudes de Amistad",
    "friends.accept": "Aceptar",
    "friends.reject": "Rechazar",
    "friends.add": "Agregar",
    "friends.already": "Amigos",
    "friends.pending": "Pendiente",
    "friends.none": "Aún no hay amigos.",
  },
  en: {
    "welcome": "welcome",
    "home": "home",
    "profile": "profile",
    "marketplace": "marketplace",
    "logout": "logout",
    "login": "login",
    "register": "register",
    "search": "Search...",
    "index.description": "Conectados em Sergipe is a social network that connects people through communities in Sergipe.",
    "index.cta": "to get started.",
    "index.register": "Register",
    "index.or": "or",
    "index.login": "Login",
    "guest_user": "Guest User",
    "login_to_see": "Login to see your profile",
    "the_wall": "The Wall",
    "write_something": "Write something:",
    "whats_on_mind": "What's on your mind?",
    "post": "Post",
    "friends": "Friends",
    "see_all_friends": "See All Friends",
    "photo": "photo",
    "profile_of": "Profile of",
    "change_photo": "Change photo",
    "click_to_change": "Click to change photo",
    "name": "Name",
    "email": "Email",
    "school": "School",
    "member_since": "Member since",
    "bio": "Bio",
    "no_bio": "No bio yet.",
    "edit_profile": "Edit Profile",
    "save": "Save",
    "cancel": "Cancel",
    "login.email": "Email:",
    "login.password": "Password:",
    "login.demo": "Demo:",
    "login.invalid": "Invalid email or password.",
    "login.welcome_title": "[ Welcome to Conectados em Sergipe ]",
    "login.welcome_text": "Conectados em Sergipe is a social network that connects people through communities in Sergipe.",
    "login.opened": "We have opened Conectados em Sergipe for everyone in",
    "login.use_for": "You can use Conectados em Sergipe to:",
    "login.feature1": "Search for people at your school",
    "login.feature2": "Find out who are in your classes",
    "login.feature3": "Look up your friends' friends",
    "login.feature4": "See a visualization of your social network",
    "login.get_started": "To get started, click below to register. If you have already registered, you can log in.",
    "login.about": "about",
    "login.welcome_bar": "Welcome to Thefacebook!",
    "register.title": "Register for [ thefacebook ]",
    "register.description": "Thefacebook is a social directory for college students.",
    "register.full_name": "Full Name:",
    "register.email": "Email:",
    "register.password": "Password:",
    "register.school": "School:",
    "register.school_placeholder": "Harvard University",
    "register.submit": "Register",
    "register.already": "Already have an account?",
    "register.login_here": "Login here",
    "register.email_exists": "An account with this email already exists.",
    "search.results_for": "Search results for",
    "search.people": "People",
    "search.shops": "Shops",
    "search.no_results": "No results found for",
    "marketplace.title": "Marketplace",
    "marketplace.sell": "+ Sell Item",
    "marketplace.cancel": "Cancel",
    "marketplace.item_title": "Title:",
    "marketplace.price": "Price:",
    "marketplace.category": "Category:",
    "marketplace.description": "Description:",
    "marketplace.post_item": "Post Item",
    "marketplace.seller": "Seller",
    "marketplace.no_items": "No items in this category.",
    "marketplace.all": "All",
    "marketplace.books": "Books",
    "marketplace.electronics": "Electronics",
    "marketplace.clothing": "Clothing",
    "marketplace.other": "Other",
    "footer.production": "a Mark Zuckerberg production",
    "footer.about": "about",
    "footer.contact": "contact",
    "footer.privacy": "privacy",
    "footer.terms": "terms",
    "sidebar.info": "Info",
    "sidebar.member_since": "Member since: February 2004",
    "sidebar.status": "Status: Student",
    "sidebar.looking_for": "Looking for: Friendship",
    "friends.requests": "Friend Requests",
    "friends.accept": "Accept",
    "friends.reject": "Reject",
    "friends.add": "Add Friend",
    "friends.already": "Friends",
    "friends.pending": "Pending",
    "friends.none": "No friends yet.",
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("pt");

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
