import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "pt" | "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Header
    "welcome": "bem-vindo",
    "home": "início",
    "profile": "perfil",
    "marketplace": "marketplace",
    "logout": "sair",
    "login": "entrar",
    "register": "cadastrar",
    "search": "Buscar...",
    // Index
    "index.description": "Conectados em Sergipe é uma rede social que conecta pessoas através de comunidades em Sergipe.",
    "index.cta": "para começar.",
    "index.register": "Cadastre-se",
    "index.or": "ou",
    "index.login": "Entre",
    "guest_user": "Visitante",
    "login_to_see": "Entre para ver seu perfil",
    // PostFeed
    "the_wall": "Destaques",
    "write_something": "Escreva algo:",
    "whats_on_mind": "O que está na sua mente?",
    "post": "Postar",
    // FriendsSidebar
    "friends": "Amigos",
    "see_all_friends": "Ver Todos os Amigos",
    "photo": "foto",
    // Profile
    "profile_of": "Perfil de",
    "change_photo": "Alterar foto",
    "click_to_change": "Clique para alterar a foto",
    "name": "Nome",
    "email": "Email",
    "school": "Escola",
    "member_since": "Membro desde",
    "bio": "Bio",
    "no_bio": "Sem bio ainda.",
    "edit_profile": "Editar Perfil",
    "save": "Salvar",
    "cancel": "Cancelar",
    // Login
    "login.email": "Email ou Telefone:",
    "login.password": "Senha:",
    "login.demo": "Demo:",
    "login.invalid": "Email/telefone ou senha inválidos.",
    "login.forgot_password": "Esqueceu a senha?",
    "login.forgot_title": "Recuperar Senha",
    "login.forgot_text": "Digite seu email para receber um link de recuperação.",
    "login.forgot_send": "Enviar link",
    "login.forgot_sent": "Email enviado! Verifique sua caixa de entrada.",
    "login.forgot_back": "Voltar ao login",
    "reset.title": "Redefinir Senha",
    "reset.new_password": "Nova senha:",
    "reset.confirm": "Confirmar senha:",
    "reset.submit": "Redefinir",
    "reset.success": "Senha redefinida com sucesso! Redirecionando...",
    "reset.mismatch": "As senhas não coincidem.",
    "reset.error": "Erro ao redefinir senha.",
    "register.phone": "Telefone (opcional):",
    "register.phone_placeholder": "+5579999999999",
    "login.welcome_title": "[ Bem-vindo ao Conectados em Sergipe ]",
    "login.welcome_text": "Conectados em Sergipe é uma rede social que conecta pessoas através de comunidades em Sergipe.",
    "login.opened": "Abrimos o Conectados em Sergipe para todos em",
    "login.use_for": "Você pode usar o Conectados em Sergipe para:",
    "login.feature1": "Buscar pessoas na sua escola",
    "login.feature2": "Descobrir quem está nas suas turmas",
    "login.feature3": "Encontrar amigos dos seus amigos",
    "login.feature4": "Ver uma visualização da sua rede social",
    "login.get_started": "Para começar, clique abaixo para se cadastrar. Se já tem conta, faça login.",
    "login.about": "sobre",
    "login.welcome_bar": "Bem-vindo ao Conectados em Sergipe!",
    // Register
    "register.title": "Cadastro no [ Conectados em Sergipe ]",
    "register.description": "Conectados em Sergipe é uma rede social para pessoas de Sergipe.",
    "register.full_name": "Nome Completo:",
    "register.email": "Email:",
    "register.password": "Senha:",
    "register.school": "Escola:",
    "register.school_placeholder": "Universidade de São Paulo",
    "register.submit": "Cadastrar",
    "register.already": "Já tem uma conta?",
    "register.login_here": "Entre aqui",
    "register.email_exists": "Já existe uma conta com este email.",
    "register.birthdate": "Data de Nascimento:",
    "register.city": "Cidade:",
    "register.select_city": "Selecione sua cidade",
    "register.min_age": "Você precisa ter pelo menos 16 anos para se cadastrar.",
    "city": "Cidade",
    "birthdate": "Nascimento",
    // Search
    "search.results_for": "Resultados da busca por",
    "search.people": "Pessoas",
    "search.shops": "Lojas",
    "search.no_results": "Nenhum resultado encontrado para",
    // Marketplace
    "marketplace.title": "Marketplace",
    "marketplace.sell": "+ Vender Item",
    "marketplace.cancel": "Cancelar",
    "marketplace.item_title": "Título:",
    "marketplace.price": "Preço:",
    "marketplace.category": "Categoria:",
    "marketplace.description": "Descrição:",
    "marketplace.post_item": "Publicar Item",
    "marketplace.seller": "Vendedor",
    "marketplace.no_items": "Nenhum item nesta categoria.",
    "marketplace.all": "Todos",
    "marketplace.books": "Livros",
    "marketplace.electronics": "Eletrônicos",
    "marketplace.clothing": "Roupas",
    "marketplace.other": "Outros",
    "marketplace.moveis": "Móveis",
    "marketplace.imoveis": "Imóveis",
    "marketplace.celulares": "Celulares",
    "marketplace.carros": "Carros",
    "marketplace.motos": "Motos",
    "marketplace.bicicletas": "Bicicletas",
    "marketplace.som": "Som",
    "marketplace.bolos_doces": "Bolos/Doces",
    "marketplace.mudas": "Mudas Frutíferas",
    "marketplace.sofa_mesa": "Sofá/Mesa/Cadeiras",
    "marketplace.fogao": "Fogão",
    "marketplace.geladeira": "Geladeira",
    "marketplace.guarda_roupa": "Guarda-Roupa",
    "marketplace.city": "Cidade:",
    "marketplace.image": "Foto do produto:",
    "marketplace.contact": "Contatar vendedor",
    "marketplace.recommended": "Recomendado para você",
    "marketplace.delete_item": "Excluir",
    "marketplace.mark_sold": "Vendido",
    "marketplace.sold_label": "VENDIDO",
    "marketplace.delete_confirm_title": "Excluir anúncio?",
    "marketplace.delete_confirm_desc": "Tem certeza que deseja excluir este anúncio? Esta ação não pode ser desfeita.",
    "marketplace.nsfw_blocked": "Imagem bloqueada: conteúdo impróprio detectado",
    "marketplace.checking_image": "Verificando imagem...",
    "marketplace.whatsapp_label": "WhatsApp (contato)",
    "marketplace.whatsapp_required": "Informe o número do WhatsApp para contato",
    "marketplace.whatsapp_message": "Olá! Tenho interesse no produto:",
    "marketplace.max_images_reached": "Limite de 5 fotos atingido",
    // Ads
    "ads.title": "Painel de Anúncios",
    "ads.credits": "créditos",
    "ads.new_campaign": "+ Nova Campanha",
    "ads.create_campaign": "Criar Campanha",
    "ads.no_items": "Você não tem itens no marketplace. Publique um item primeiro.",
    "ads.select_product": "Produto:",
    "ads.choose_item": "Escolha um item",
    "ads.budget": "Orçamento",
    "ads.available": "Disponível",
    "ads.target_city": "Cidade alvo:",
    "ads.all_cities": "Todas as cidades",
    "ads.target_category": "Categoria alvo:",
    "ads.all_categories": "Todas as categorias",
    "ads.launch": "Lançar Campanha",
    "ads.no_campaigns": "Nenhuma campanha criada.",
    "ads.active": "Ativo",
    "ads.paused": "Pausado",
    "ads.ended": "Encerrado",
    "ads.impressions": "Impressões",
    "ads.clicks": "Cliques",
    "ads.spent_budget": "Gasto/Orçam.",
    "ads.pause": "Pausar",
    "ads.resume": "Retomar",
    "ads.sponsored": "Patrocinado",
    "ads.my_ads": "Meus Anúncios",
    // Footer
    "footer.production": "uma produção Jairo dos Santos",
    "footer.about": "sobre",
    "footer.contact": "contato",
    "footer.privacy": "privacidade",
    "footer.terms": "termos",
    // ProfileSidebar
    "sidebar.info": "Info",
    "sidebar.member_since": "Membro desde: Fevereiro 2004",
    "sidebar.status": "Status: Estudante",
    "sidebar.looking_for": "Buscando: Amizade",
    // Friends
    "friends.requests": "Pedidos de Amizade",
    "friends.accept": "Aceitar",
    "friends.reject": "Recusar",
    "friends.add": "Adicionar",
    "friends.already": "Amigos",
    "friends.pending": "Pendente",
    "friends.none": "Nenhum amigo ainda.",
    "comments.show": "Comentários",
    "comments.hide": "Ocultar comentários",
    "comments.placeholder": "Escreva um comentário...",
    "comments.send": "Enviar",
    "admin.delete_post": "Excluir post",
    "admin.ban_user": "Banir usuário",
    "admin.ban_days": "Duração do ban",
    "admin.ban_reason": "Motivo",
    "admin.confirm_ban": "Confirmar Ban",
    "admin.day": "dia",
    "admin.days": "dias",
    "admin.year": "ano",
    "admin.follow": "Seguir",
    "admin.unfollow": "Deixar de seguir",
    "admin.followers": "Seguidores",
    "admin.panel_title": "Painel de Administração",
    "admin.active_bans": "Bans Ativos",
    "admin.expired_bans": "Bans Expirados",
    "admin.loading": "Carregando...",
    "admin.no_bans": "Nenhum ban encontrado.",
    "admin.banned_user": "Usuário banido",
    "admin.banned_by_label": "Banido por",
    "admin.banned_at": "Data do ban",
    "admin.banned_until_label": "Banido até",
    "admin.unban": "Remover Ban",
    "admin.panel": "Admin",
    "admin.reports": "Denúncias",
    "admin.pending_reports": "Pendentes",
    "admin.resolved_reports": "Resolvidas",
    "admin.no_reports": "Nenhuma denúncia encontrada.",
    "admin.report_by": "Denunciado por",
    "admin.report_reason": "Motivo",
    "admin.report_content_type": "Tipo",
    "admin.report_date": "Data",
    "admin.resolve_report": "Resolver",
    "admin.dismiss_report": "Dispensar",
    "admin.pages": "Páginas",
    "admin.pages_tab": "📄 Páginas",
    "admin.edit_page": "Editar",
    "admin.save_page": "Salvar",
    "admin.page_saved": "Página salva com sucesso!",
    "admin.page_save_error": "Erro ao salvar página.",
    "admin.page_content": "Conteúdo",
    "report.button": "Denunciar",
    "report.title": "Denunciar conteúdo",
    "report.adult_content": "Conteúdo adulto",
    "report.spam": "Spam",
    "report.violence": "Violência",
    "report.hate_speech": "Discurso de ódio",
    "report.sent": "Denúncia enviada com sucesso!",
    "report.error": "Erro ao enviar denúncia.",
    "public_profile.not_found": "Usuário não encontrado.",
    "messages": "Mensagens",
    "messages.title": "Mensagens",
    "messages.no_conversations": "Nenhuma conversa ainda.",
    "messages.select_conversation": "Selecione uma conversa para começar.",
    "messages.placeholder": "Digite sua mensagem...",
    "messages.send": "Enviar",
    "messages.send_message": "Enviar mensagem",
    "post.edit": "Editar",
    "post.delete": "Excluir",
    "post.delete_confirm": "Tem certeza que deseja excluir este post?",
    "post.add_photo": "Foto",
    "post.max_5mb": "máx. 5MB",
    "post.uploading": "Enviando...",
    "post.image_too_large": "Imagem muito grande! Máximo 5MB.",
    "post.image_error": "Erro ao processar imagem.",
  },
  es: {
    "welcome": "bienvenido",
    "home": "inicio",
    "profile": "perfil",
    "marketplace": "marketplace",
    "logout": "salir",
    "login": "entrar",
    "register": "registrarse",
    "search": "Buscar...",
    "index.description": "Conectados en Sergipe es una red social que conecta personas a través de comunidades en Sergipe.",
    "index.cta": "para empezar.",
    "index.register": "Regístrate",
    "index.or": "o",
    "index.login": "Inicia sesión",
    "guest_user": "Visitante",
    "login_to_see": "Inicia sesión para ver tu perfil",
    "the_wall": "Destacados",
    "write_something": "Escribe algo:",
    "whats_on_mind": "¿Qué tienes en mente?",
    "post": "Publicar",
    "friends": "Amigos",
    "see_all_friends": "Ver Todos los Amigos",
    "photo": "foto",
    "profile_of": "Perfil de",
    "change_photo": "Cambiar foto",
    "click_to_change": "Haz clic para cambiar la foto",
    "name": "Nombre",
    "email": "Correo",
    "school": "Universidad",
    "member_since": "Miembro desde",
    "bio": "Bio",
    "no_bio": "Sin bio todavía.",
    "edit_profile": "Editar Perfil",
    "save": "Guardar",
    "cancel": "Cancelar",
    "login.email": "Correo o Teléfono:",
    "login.password": "Contraseña:",
    "login.demo": "Demo:",
    "login.invalid": "Correo/teléfono o contraseña inválidos.",
    "login.forgot_password": "¿Olvidó la contraseña?",
    "login.forgot_title": "Recuperar Contraseña",
    "login.forgot_text": "Ingrese su correo para recibir un enlace de recuperación.",
    "login.forgot_send": "Enviar enlace",
    "login.forgot_sent": "¡Correo enviado! Revise su bandeja de entrada.",
    "login.forgot_back": "Volver al login",
    "reset.title": "Restablecer Contraseña",
    "reset.new_password": "Nueva contraseña:",
    "reset.confirm": "Confirmar contraseña:",
    "reset.submit": "Restablecer",
    "reset.success": "¡Contraseña restablecida! Redirigiendo...",
    "reset.mismatch": "Las contraseñas no coinciden.",
    "reset.error": "Error al restablecer la contraseña.",
    "register.phone": "Teléfono (opcional):",
    "register.phone_placeholder": "+5579999999999",
    "login.welcome_title": "[ Bienvenido a Conectados en Sergipe ]",
    "login.welcome_text": "Conectados en Sergipe es una red social que conecta personas a través de comunidades en Sergipe.",
    "login.opened": "Hemos abierto Conectados en Sergipe para todos en",
    "login.use_for": "Puedes usar Conectados en Sergipe para:",
    "login.feature1": "Buscar personas en tu universidad",
    "login.feature2": "Descubrir quién está en tus clases",
    "login.feature3": "Encontrar amigos de tus amigos",
    "login.feature4": "Ver una visualización de tu red social",
    "login.get_started": "Para empezar, haz clic abajo para registrarte. Si ya tienes cuenta, inicia sesión.",
    "login.about": "acerca de",
    "login.welcome_bar": "¡Bienvenido a Conectados en Sergipe!",
    "register.title": "Registro en [ Conectados en Sergipe ]",
    "register.description": "Conectados en Sergipe es una red social para personas de Sergipe.",
    "register.full_name": "Nombre Completo:",
    "register.email": "Correo:",
    "register.password": "Contraseña:",
    "register.school": "Universidad:",
    "register.school_placeholder": "Universidad de Buenos Aires",
    "register.submit": "Registrarse",
    "register.already": "¿Ya tienes una cuenta?",
    "register.login_here": "Inicia sesión aquí",
    "register.email_exists": "Ya existe una cuenta con este correo.",
    "register.birthdate": "Fecha de Nacimiento:",
    "register.city": "Ciudad:",
    "register.select_city": "Seleccione su ciudad",
    "register.min_age": "Debes tener al menos 16 años para registrarte.",
    "city": "Ciudad",
    "birthdate": "Nacimiento",
    "search.results_for": "Resultados de búsqueda para",
    "search.people": "Personas",
    "search.shops": "Tiendas",
    "search.no_results": "No se encontraron resultados para",
    "marketplace.title": "Marketplace",
    "marketplace.sell": "+ Vender Artículo",
    "marketplace.cancel": "Cancelar",
    "marketplace.item_title": "Título:",
    "marketplace.price": "Precio:",
    "marketplace.category": "Categoría:",
    "marketplace.description": "Descripción:",
    "marketplace.post_item": "Publicar Artículo",
    "marketplace.seller": "Vendedor",
    "marketplace.no_items": "No hay artículos en esta categoría.",
    "marketplace.all": "Todos",
    "marketplace.books": "Libros",
    "marketplace.electronics": "Electrónicos",
    "marketplace.clothing": "Ropa",
    "marketplace.other": "Otros",
    "marketplace.moveis": "Muebles",
    "marketplace.imoveis": "Inmuebles",
    "marketplace.celulares": "Celulares",
    "marketplace.carros": "Autos",
    "marketplace.motos": "Motos",
    "marketplace.bicicletas": "Bicicletas",
    "marketplace.som": "Sonido",
    "marketplace.bolos_doces": "Pasteles/Dulces",
    "marketplace.mudas": "Plantas Frutales",
    "marketplace.sofa_mesa": "Sofá/Mesa/Sillas",
    "marketplace.fogao": "Cocina",
    "marketplace.geladeira": "Refrigerador",
    "marketplace.guarda_roupa": "Armario",
    "marketplace.city": "Ciudad:",
    "marketplace.image": "Foto del producto:",
    "marketplace.contact": "Contactar vendedor",
    "marketplace.recommended": "Recomendado para ti",
    "marketplace.delete_item": "Eliminar",
    "marketplace.mark_sold": "Vendido",
    "marketplace.sold_label": "VENDIDO",
    "marketplace.delete_confirm_title": "¿Eliminar anuncio?",
    "marketplace.delete_confirm_desc": "¿Estás seguro de que deseas eliminar este anuncio? Esta acción no se puede deshacer.",
    "marketplace.nsfw_blocked": "Imagen bloqueada: contenido inapropiado detectado",
    "marketplace.checking_image": "Verificando imagen...",
    "marketplace.whatsapp_label": "WhatsApp (contacto)",
    "marketplace.whatsapp_required": "Ingrese el número de WhatsApp de contacto",
    "marketplace.whatsapp_message": "¡Hola! Estoy interesado en el producto:",
    "marketplace.max_images_reached": "Límite de 5 fotos alcanzado",
    "ads.title": "Panel de Anuncios",
    "ads.credits": "créditos",
    "ads.new_campaign": "+ Nueva Campaña",
    "ads.create_campaign": "Crear Campaña",
    "ads.no_items": "No tienes artículos en el marketplace. Publica uno primero.",
    "ads.select_product": "Producto:",
    "ads.choose_item": "Elige un artículo",
    "ads.budget": "Presupuesto",
    "ads.available": "Disponible",
    "ads.target_city": "Ciudad objetivo:",
    "ads.all_cities": "Todas las ciudades",
    "ads.target_category": "Categoría objetivo:",
    "ads.all_categories": "Todas las categorías",
    "ads.launch": "Lanzar Campaña",
    "ads.no_campaigns": "No hay campañas creadas.",
    "ads.active": "Activo",
    "ads.paused": "Pausado",
    "ads.ended": "Finalizado",
    "ads.impressions": "Impresiones",
    "ads.clicks": "Clics",
    "ads.spent_budget": "Gastado/Presup.",
    "ads.pause": "Pausar",
    "ads.resume": "Reanudar",
    "ads.sponsored": "Patrocinado",
    "ads.my_ads": "Mis Anuncios",
    "footer.production": "una producción de Jairo dos Santos",
    "footer.about": "acerca de",
    "footer.contact": "contacto",
    "footer.privacy": "privacidad",
    "footer.terms": "términos",
    "sidebar.info": "Info",
    "sidebar.member_since": "Miembro desde: Febrero 2004",
    "sidebar.status": "Estado: Estudiante",
    "sidebar.looking_for": "Buscando: Amistad",
    "friends.requests": "Solicitudes de Amistad",
    "friends.accept": "Aceptar",
    "friends.reject": "Rechazar",
    "friends.add": "Agregar",
    "friends.already": "Amigos",
    "friends.pending": "Pendiente",
    "friends.none": "Aún no hay amigos.",
    "comments.show": "Comentarios",
    "comments.hide": "Ocultar comentarios",
    "comments.placeholder": "Escribe un comentario...",
    "comments.send": "Enviar",
    "admin.delete_post": "Eliminar post",
    "admin.ban_user": "Banear usuario",
    "admin.ban_days": "Duración del ban",
    "admin.ban_reason": "Razón",
    "admin.confirm_ban": "Confirmar Ban",
    "admin.day": "día",
    "admin.days": "días",
    "admin.year": "año",
    "admin.follow": "Seguir",
    "admin.unfollow": "Dejar de seguir",
    "admin.followers": "Seguidores",
    "admin.panel_title": "Panel de Administración",
    "admin.active_bans": "Bans Activos",
    "admin.expired_bans": "Bans Expirados",
    "admin.loading": "Cargando...",
    "admin.no_bans": "No se encontraron bans.",
    "admin.banned_user": "Usuario baneado",
    "admin.banned_by_label": "Baneado por",
    "admin.banned_at": "Fecha del ban",
    "admin.banned_until_label": "Baneado hasta",
    "admin.unban": "Remover Ban",
    "admin.panel": "Admin",
    "admin.reports": "Denuncias",
    "admin.pending_reports": "Pendientes",
    "admin.resolved_reports": "Resueltas",
    "admin.no_reports": "No se encontraron denuncias.",
    "admin.report_by": "Denunciado por",
    "admin.report_reason": "Motivo",
    "admin.report_content_type": "Tipo",
    "admin.report_date": "Fecha",
    "admin.resolve_report": "Resolver",
    "admin.dismiss_report": "Descartar",
    "admin.pages": "Páginas",
    "admin.pages_tab": "📄 Páginas",
    "admin.edit_page": "Editar",
    "admin.save_page": "Guardar",
    "admin.page_saved": "¡Página guardada con éxito!",
    "admin.page_save_error": "Error al guardar la página.",
    "admin.page_content": "Contenido",
    "report.button": "Denunciar",
    "report.title": "Denunciar contenido",
    "report.adult_content": "Contenido adulto",
    "report.spam": "Spam",
    "report.violence": "Violencia",
    "report.hate_speech": "Discurso de odio",
    "report.sent": "¡Denuncia enviada con éxito!",
    "report.error": "Error al enviar denuncia.",
    "public_profile.not_found": "Usuario no encontrado.",
    "messages": "Mensajes",
    "messages.title": "Mensajes",
    "messages.no_conversations": "Sin conversaciones aún.",
    "messages.select_conversation": "Seleccione una conversación para comenzar.",
    "messages.placeholder": "Escribe tu mensaje...",
    "messages.send": "Enviar",
    "messages.send_message": "Enviar mensaje",
    "post.edit": "Editar",
    "post.delete": "Eliminar",
    "post.delete_confirm": "¿Estás seguro de que deseas eliminar esta publicación?",
    "post.add_photo": "Foto",
    "post.max_5mb": "máx. 5MB",
    "post.uploading": "Subiendo...",
    "post.image_too_large": "¡Imagen demasiado grande! Máximo 5MB.",
    "post.image_error": "Error al procesar la imagen.",
  },
  en: {
    "welcome": "welcome",
    "home": "home",
    "profile": "profile",
    "marketplace": "marketplace",
    "logout": "logout",
    "login": "login",
    "register": "register",
    "search": "Search...",
    "index.description": "Conectados em Sergipe is a social network that connects people through communities in Sergipe.",
    "index.cta": "to get started.",
    "index.register": "Register",
    "index.or": "or",
    "index.login": "Login",
    "guest_user": "Guest User",
    "login_to_see": "Login to see your profile",
    "the_wall": "Highlights",
    "write_something": "Write something:",
    "whats_on_mind": "What's on your mind?",
    "post": "Post",
    "friends": "Friends",
    "see_all_friends": "See All Friends",
    "photo": "photo",
    "profile_of": "Profile of",
    "change_photo": "Change photo",
    "click_to_change": "Click to change photo",
    "name": "Name",
    "email": "Email",
    "school": "School",
    "member_since": "Member since",
    "bio": "Bio",
    "no_bio": "No bio yet.",
    "edit_profile": "Edit Profile",
    "save": "Save",
    "cancel": "Cancel",
    "login.email": "Email or Phone:",
    "login.password": "Password:",
    "login.demo": "Demo:",
    "login.invalid": "Invalid email/phone or password.",
    "login.forgot_password": "Forgot password?",
    "login.forgot_title": "Recover Password",
    "login.forgot_text": "Enter your email to receive a recovery link.",
    "login.forgot_send": "Send link",
    "login.forgot_sent": "Email sent! Check your inbox.",
    "login.forgot_back": "Back to login",
    "reset.title": "Reset Password",
    "reset.new_password": "New password:",
    "reset.confirm": "Confirm password:",
    "reset.submit": "Reset",
    "reset.success": "Password reset successfully! Redirecting...",
    "reset.mismatch": "Passwords do not match.",
    "reset.error": "Error resetting password.",
    "register.phone": "Phone (optional):",
    "register.phone_placeholder": "+5579999999999",
    "login.welcome_title": "[ Welcome to Conectados em Sergipe ]",
    "login.welcome_text": "Conectados em Sergipe is a social network that connects people through communities in Sergipe.",
    "login.opened": "We have opened Conectados em Sergipe for everyone in",
    "login.use_for": "You can use Conectados em Sergipe to:",
    "login.feature1": "Search for people at your school",
    "login.feature2": "Find out who are in your classes",
    "login.feature3": "Look up your friends' friends",
    "login.feature4": "See a visualization of your social network",
    "login.get_started": "To get started, click below to register. If you have already registered, you can log in.",
    "login.about": "about",
    "login.welcome_bar": "Welcome to Conectados em Sergipe!",
    "register.title": "Register for [ Conectados em Sergipe ]",
    "register.description": "Conectados em Sergipe is a social network for people in Sergipe.",
    "register.full_name": "Full Name:",
    "register.email": "Email:",
    "register.password": "Password:",
    "register.school": "School:",
    "register.school_placeholder": "Harvard University",
    "register.submit": "Register",
    "register.already": "Already have an account?",
    "register.login_here": "Login here",
    "register.email_exists": "An account with this email already exists.",
    "register.birthdate": "Date of Birth:",
    "register.city": "City:",
    "register.select_city": "Select your city",
    "register.min_age": "You must be at least 16 years old to register.",
    "city": "City",
    "birthdate": "Birthday",
    "search.results_for": "Search results for",
    "search.people": "People",
    "search.shops": "Shops",
    "search.no_results": "No results found for",
    "marketplace.title": "Marketplace",
    "marketplace.sell": "+ Sell Item",
    "marketplace.cancel": "Cancel",
    "marketplace.item_title": "Title:",
    "marketplace.price": "Price:",
    "marketplace.category": "Category:",
    "marketplace.description": "Description:",
    "marketplace.post_item": "Post Item",
    "marketplace.seller": "Seller",
    "marketplace.no_items": "No items in this category.",
    "marketplace.all": "All",
    "marketplace.books": "Books",
    "marketplace.electronics": "Electronics",
    "marketplace.clothing": "Clothing",
    "marketplace.other": "Other",
    "marketplace.moveis": "Furniture",
    "marketplace.imoveis": "Real Estate",
    "marketplace.celulares": "Phones",
    "marketplace.carros": "Cars",
    "marketplace.motos": "Motorcycles",
    "marketplace.bicicletas": "Bicycles",
    "marketplace.som": "Audio",
    "marketplace.bolos_doces": "Cakes/Sweets",
    "marketplace.mudas": "Fruit Plants",
    "marketplace.sofa_mesa": "Sofa/Table/Chairs",
    "marketplace.fogao": "Stove",
    "marketplace.geladeira": "Refrigerator",
    "marketplace.guarda_roupa": "Wardrobe",
    "marketplace.city": "City:",
    "marketplace.image": "Product photo:",
    "marketplace.contact": "Contact seller",
    "marketplace.recommended": "Recommended for you",
    "marketplace.delete_item": "Delete",
    "marketplace.mark_sold": "Sold",
    "marketplace.sold_label": "SOLD",
    "marketplace.delete_confirm_title": "Delete listing?",
    "marketplace.delete_confirm_desc": "Are you sure you want to delete this listing? This action cannot be undone.",
    "marketplace.nsfw_blocked": "Image blocked: inappropriate content detected",
    "marketplace.checking_image": "Checking image...",
    "marketplace.whatsapp_label": "WhatsApp (contact)",
    "marketplace.whatsapp_required": "Please enter a WhatsApp contact number",
    "marketplace.whatsapp_message": "Hi! I'm interested in the product:",
    "marketplace.max_images_reached": "Maximum of 5 photos reached",
    "ads.title": "Ads Dashboard",
    "ads.credits": "credits",
    "ads.new_campaign": "+ New Campaign",
    "ads.create_campaign": "Create Campaign",
    "ads.no_items": "You have no marketplace items. Publish one first.",
    "ads.select_product": "Product:",
    "ads.choose_item": "Choose an item",
    "ads.budget": "Budget",
    "ads.available": "Available",
    "ads.target_city": "Target city:",
    "ads.all_cities": "All cities",
    "ads.target_category": "Target category:",
    "ads.all_categories": "All categories",
    "ads.launch": "Launch Campaign",
    "ads.no_campaigns": "No campaigns created.",
    "ads.active": "Active",
    "ads.paused": "Paused",
    "ads.ended": "Ended",
    "ads.impressions": "Impressions",
    "ads.clicks": "Clicks",
    "ads.spent_budget": "Spent/Budget",
    "ads.pause": "Pause",
    "ads.resume": "Resume",
    "ads.sponsored": "Sponsored",
    "ads.my_ads": "My Ads",
    "footer.production": "a Jairo dos Santos production",
    "footer.about": "about",
    "footer.contact": "contact",
    "footer.privacy": "privacy",
    "footer.terms": "terms",
    "sidebar.info": "Info",
    "sidebar.member_since": "Member since: February 2004",
    "sidebar.status": "Status: Student",
    "sidebar.looking_for": "Looking for: Friendship",
    "friends.requests": "Friend Requests",
    "friends.accept": "Accept",
    "friends.reject": "Reject",
    "friends.add": "Add Friend",
    "friends.already": "Friends",
    "friends.pending": "Pending",
    "friends.none": "No friends yet.",
    "comments.show": "Comments",
    "comments.hide": "Hide comments",
    "comments.placeholder": "Write a comment...",
    "comments.send": "Send",
    "admin.delete_post": "Delete post",
    "admin.ban_user": "Ban user",
    "admin.ban_days": "Ban duration",
    "admin.ban_reason": "Reason",
    "admin.confirm_ban": "Confirm Ban",
    "admin.day": "day",
    "admin.days": "days",
    "admin.year": "year",
    "admin.follow": "Follow",
    "admin.unfollow": "Unfollow",
    "admin.followers": "Followers",
    "admin.panel_title": "Admin Panel",
    "admin.active_bans": "Active Bans",
    "admin.expired_bans": "Expired Bans",
    "admin.loading": "Loading...",
    "admin.no_bans": "No bans found.",
    "admin.banned_user": "Banned user",
    "admin.banned_by_label": "Banned by",
    "admin.banned_at": "Ban date",
    "admin.banned_until_label": "Banned until",
    "admin.unban": "Remove Ban",
    "admin.panel": "Admin",
    "admin.reports": "Reports",
    "admin.pending_reports": "Pending",
    "admin.resolved_reports": "Resolved",
    "admin.no_reports": "No reports found.",
    "admin.report_by": "Reported by",
    "admin.report_reason": "Reason",
    "admin.report_content_type": "Type",
    "admin.report_date": "Date",
    "admin.resolve_report": "Resolve",
    "admin.dismiss_report": "Dismiss",
    "admin.pages": "Pages",
    "admin.pages_tab": "📄 Pages",
    "admin.edit_page": "Edit",
    "admin.save_page": "Save",
    "admin.page_saved": "Page saved successfully!",
    "admin.page_save_error": "Error saving page.",
    "admin.page_content": "Content",
    "report.button": "Report",
    "report.title": "Report content",
    "report.adult_content": "Adult content",
    "report.spam": "Spam",
    "report.violence": "Violence",
    "report.hate_speech": "Hate speech",
    "report.sent": "Report submitted successfully!",
    "report.error": "Error submitting report.",
    "public_profile.not_found": "User not found.",
    "messages": "Messages",
    "messages.title": "Messages",
    "messages.no_conversations": "No conversations yet.",
    "messages.select_conversation": "Select a conversation to start.",
    "messages.placeholder": "Type your message...",
    "messages.send": "Send",
    "messages.send_message": "Send message",
    "post.edit": "Edit",
    "post.delete": "Delete",
    "post.delete_confirm": "Are you sure you want to delete this post?",
    "post.add_photo": "Photo",
    "post.max_5mb": "max 5MB",
    "post.uploading": "Uploading...",
    "post.image_too_large": "Image too large! Max 5MB.",
    "post.image_error": "Error processing image.",
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("pt");

  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
